-- Run this in your Supabase SQL Editor to create the reports table

CREATE TABLE public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    platform TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Under Review',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    report_count INTEGER NOT NULL DEFAULT 1,
    is_anonymous BOOLEAN NOT NULL DEFAULT true,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) but allow anonymous inserts and reads for this specific project
-- (For a real production app, you would restrict inserts to authenticated users or add captcha/rate limits)

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read access"
ON public.reports FOR SELECT
USING (true);

CREATE POLICY "Allow anonymous insert access"
ON public.reports FOR INSERT
WITH CHECK (true);

CREATE POLICY "Allow public update access for admin simulation"
ON public.reports FOR UPDATE
USING (true)
WITH CHECK (true);
